name: Issue Created
on:
  issues:
    types:
      - opened
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "${{ toJSON(github) }}"
