name: lint
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: action/checkout@v4
            - name: Install NodeJs
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm lint
    test:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Get Code
          uses: action/checkout@v4
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm test
    build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Get Code
          uses: action/checkout@v4
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run build
          run: npm build
