name: lint test build
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJs
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint
    test:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm run test
    build:
      runs-on: ubuntu-latest
      needs: test
      outputs:
        asset-files: ${{steps.publish.outputs.script-files}}
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run build
          run: npm run build
        - name: Publish JS filename
          id: publish
          run: find dist/assets/*.js -type f -execdir echo 'script-files={}' >> $GITHUB_OUTPUT ';'
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: dist
#            path: |
#              dist
#              package.json
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get Artifact
          uses: actions/download-artifact@v4
          with:
            name: my-artifact
        - name: Output contents
          run: ls
        - name: Output asset files
          run: echo "${{ needs.build.outputs.asset-files }}"
        - name: Deploy
          run: echo "Deploying..."
